# Generated by Django 4.2.9 on 2024-02-24 11:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Powerline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=45)),
                ("datetime", models.DateField()),
                ("photo_of_powerline", models.CharField(max_length=1000)),
                ("has_transformer", models.BooleanField(default=False)),
                (
                    "condition_of_transformer",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                (
                    "photo_of_transformer",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("has_broken_powercables", models.BooleanField(default=False)),
                ("count_of_broken_cables", models.IntegerField(blank=True, null=True)),
                (
                    "photo_of_powercables",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("altitude", models.FloatField(blank=True, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PowerlineIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_type", models.CharField(max_length=100)),
                ("severity", models.CharField(max_length=45)),
                ("date_of_occurrence", models.DateField()),
                ("time_of_occurrence", models.TimeField()),
                ("photo_of_incident", models.CharField(max_length=1000)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
        ),
    ]
