# Generated by Django 4.2.9 on 2024-02-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="powerlineincident",
            name="date_of_occurrence",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="powerlineincident",
            name="time_of_occurrence",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
