# Generated by Django 4.2.9 on 2024-03-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_api", "0002_alter_powerlineincident_date_of_occurrence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="powerline",
            name="structural_type",
            field=models.CharField(default="Wooden", max_length=45),
        ),
    ]
